apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-inspect.fullname" . }}-config
data:
  kubeinspect.yaml: |
    kube_resources:
      - id: {{.Values.app.atwinSession.atc }}
        path: "/atc"
        group: "atwin.airlab.com"
        version: "v1alpha1"
        kind: "Atcatwin"
      - id: {{.Values.app.atwinSession.proto }}
        path: "/proto"
        group: "atwin.airlab.com"
        version: "v1alpha1"
        kind: "Protoatwin"
      - id: {{.Values.app.atwinSession.sim }}
        path: "/sim"
        group: "atwin.airlab.com"
        version: "v1alpha1"
        kind: "Simatwin"
      - id: {{.Values.app.atwinSession.minimart }}
        path: "/minimart"
        group: "sample.airlab.com"
        version: "v1beta1"
        kind: "Minimart"
    engine:
      httpport: {{ .Values.app.httpport }}
