apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-inspect.fullname" . }}-config
data:
  kubeinspect.yaml: |
    kube_resources:
      - id: pod
        path: "{{ .Values.app.paths.pods }}"
      - id: deployment
        path: "{{ .Values.app.paths.deps }}"
      - id: service
        path: "{{ .Values.app.paths.services }}"
    engine:
      httpport: {{ .Values.app.httpport }}
