apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummyservices.atwin.airlab.aero
spec:
  group: atwin.airlab.aero
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Define attributes the dummy services assembly should have
              type: object
              properties:
                sessionState:
                  type: string
                sessionTemplateId:
                  type: string
                sessionId:
                  type: string
                assemblyType:
                  type: string
                used:
                  type: boolean
                capabilities:
                  type: array
                  items:
                    type: object
                    properties:
                      state:
                        type: string
                      capabilityType:
                        type: string
                      replicaCount:
                        type: integer
  scope: Namespaced
  names:
    plural: dummyservices
    singular: dummyservice
    kind: Dummyservice
    shortNames:
      - ds