# permissions for end users to view minimarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimart-viewer-role
rules:
- apiGroups:
  - charts.samutup.com
  resources:
  - minimarts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.samutup.com
  resources:
  - minimarts/status
  verbs:
  - get
