apiVersion: attwin.airlab.aero/v1alpha1
kind: Dummyservice
metadata:
  name: s2
spec:
  # Default values copied from <project_dir>/helm-charts/dummyservice/values.yaml
  affinity: {}
  app:
    httpport: 8002
    rest:
      bev: /minimart-bev
      stat: /minimart-stat
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    repository: samutup/minimart
    tag: 1.0.2
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - backend:
          serviceName: chart-example.local
          servicePort: 80
        path: /
    tls: []
  nameOverride: ""
  namespace: minimart
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    ports:
      debug_port: 30842
      http_port: 30841
    type: NodePort
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  sessionId: s2
  assemblyType: "dummy"
  used: true
  capabilities:
    - state: STOPPED
      capabilityType: fp
      replicaCount: 3
  
  
