apiVersion: atwin.airlab.aero/v1alpha1
kind: Dummyservice
metadata:
  name: dummy-s2
spec:
  # Default values copied from <project_dir>/helm-charts/dummyservice/values.yaml
  affinity: {}
  app:
    httpport: 8002
    rest:
      bev: /minimart-bev
      stat: /minimart-stat
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    repository: samutup/minimart
    tag: 1.0.2
  imagePullSecrets:
   - name: registry
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - backend:
          serviceName: chart-example.local
          servicePort: 80
        path: /
    tls: []
  nameOverride: ""
  namespace: minimart
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 80
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  sessionId: s2
  assemblyType: "dummy"
  used: true
  capabilities:
  - state: STOPPED
    capabilityType: fp
    replicaCount: 3
  #sessionId: sess-1
  #assemblyType: dummy
  #capabilities:
  #- capabilityType: st
  #  replicaCount: 3
  #  state: STOPPED
  #used: true

  
  
