# permissions for end users to view dummyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummyservice-viewer-role
rules:
- apiGroups:
  - atwin.airlab.aero
  resources:
  - dummyservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - atwin.airlab.aero
  resources:
  - dummyservices/status
  verbs:
  - get
